### ISSUE TITLE
*-command not highlighted after THEN or ELSE

### ISSUE THREAD

**Issue by ojwb** [mattgodbolt/owlet-editor#112]
This example shows we aren't highlighting a *-command after `THEN` or `ELSE` - I suspect we need to switch to statement mode there too:

https://bbcmic.ro/#%7B%22v%22%3A1%2C%22program%22%3A%22IF1THEN*H.%5CnIF0ELSE*H.%22%7D

(This may be related to #37/#110 - I'm not sure if these cases worked before that or not...)

**Comment by mattgodbolt** [comment]
Nice find!

**Comment by ojwb** [comment]
I thought we'd discussed this quite some time ago and concluded we probably ought to be checking the `Start` flag bit in the token list to detect these.  However looking at that bit again I notice it is set for `LET` but `LET*HELP` isn't valid.  Perhaps that's OK as `ELSE*HELP` (with no `IF`) is also not valid but coloured as a *-command.  (I think ideally any syntax error would be coloured to flag there's an error, but that's getting that to happen for all cases seems likely to be hard without implementing quite a lot of a BASIC interpreter in JS, or perhaps emulating suitable 6502 code in the BASIC ROM.)

Looking at other tokens with that bit set it seems the only token which really starts a new statement which we don't yet handle is `ERROR`:

```
ONERROR*HELP
```

Abbreviations also aren't correctly handled yet though, e.g.:

```
IF0EL.*H.
IF0TH.*H.
IF0ELS.*H.
IF0THE.*H.
```

And putting the two together:

```
ONERRO.*HELP
ONERR.*HELP
```

I can probably come up with a patch.
