### ISSUE TITLE
Highlighting numbers in exponential notation

### ISSUE THREAD

**Issue by ojwb** [mattgodbolt/owlet-editor#26]
Currently `Z%=2E4` highlights `2` as a number but `E4` as a variable.  I think `2E4` should be highlighted as a number.

**Comment by ojwb** [comment]
I spotted a case where this causes the highlighter to really lose the plot - in `FORJ%=2E4TO22400STEP100` the whole of `E4TO22400STEP100` is highlighted as a variable!

**Comment by mattgodbolt** [comment]
Thanks!
