### ISSUE TITLE
Highlighting of decimal point corner cases

### ISSUE THREAD

**Issue by ojwb** [mattgodbolt/owlet-editor#27]
Consider:

```
P.1.,.5,.
```

Here `.5` is highlighted as a number (good), but in `1.` the `.` is red, and `.` by itself is also red (but this is really the same as `0.0` as you can see if you run this program).  I think `1.` and `.` should both be highlighted as numbers.

**Comment by mattgodbolt** [comment]
TIL `.` on its own is `0` :)
