### ISSUE TITLE
ASM example

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/owlet-editor#33]
https://bbcmic.ro/#%7B%22v%22%3A1%2C%22program%22%3A%22DIM%20MC%25%20400%3AFOR%20O%25%3D0%20TO%203%20STEP%203%3AP%25%3DMC%25%3A%5B%3AOPT%20O%25%3A.H%25%20EQUW%20%2655AA%3A.S%25%20EQUW%20%263000%3A.Y%25%20EQUD%20%26FCF0C000%3AEQUD%20%26030F3FFF%3A.g%20LDA%20S%25%3ASTA%20%2670%3ALDA%20S%25%2B1%3ASTA%20%2671%3ALDY%20%230%3A.t%20LDA%20H%25%3ASTA%20(%2670)%2CY%3AINY%3ALDA%20H%25%2B1%3ASTA%20(%2670)%2CY%3AINY%3ABNE%20t%3ALDY%20%230%3AINC%20%2671%3ABPL%20t%3A.c%20LDA%20S%25%3ACLC%5CnADC%20%2332%3ASTA%20%2676%3ALDA%20S%25%2B1%3ASTA%20%2677%3ALDA%20%230%3ASTA%20%2672%3A.a%20ASL%20A%3AAND%20%237%3ASTA%20%2673%3ALDA%20%2676%3ASTA%20%2678%3ALDA%20%2677%3ASTA%20%2679%3ALDA%20%230%3ASTA%20%2674%3A.l%20LDA%20%2678%3ASTA%20%267A%3ALDA%20%2679%3ASTA%20%267B%3ALDA%20%2673%3ACLC%3AADC%20%267C%3AAND%20%23%267%3ATAY%3ALDA%20Y%25%2CY%3ALDY%20%230%3ASTA%20(%267A)%2CY%3AINY%3ASTA%20(%267A)%2CY%3AINY%3ASTA%20(%267A)%2CY%3AINY%3ASTA%20(%267A)%2CY%5CnINY%3ASTA%20(%267A)%2CY%3AINY%3ASTA%20(%267A)%2CY%3AINY%3ASTA%20(%267A)%2CY%3AINY%3ASTA%20(%267A)%2CY%3ALDA%20%23%26F0%3ABIT%20%2674%3ABNE%20e%3ALDA%20%23%262%3ABIT%20%2672%3ABNE%20k%3AJMP%20f%3A.e%20LDA%20%23%262%3ABIT%20%2672%3ABNE%20f%3AJMP%20k%3A.f%20LDA%20%2673%3ACLC%3AADC%20%231%3AAND%20%237%3ASTA%20%2673%3AJMP%20i%3A.k%20LDA%20%2673%3ACLC%3AADC%20%237%3AAND%20%237%3ASTA%20%2673%3A.i%20CLC%3ALDA%20%2678%3AADC%20%23%2680%3ASTA%20%2678%5CnLDA%20%2679%3AADC%20%232%3ASTA%20%2679%3ALDA%20%2674%3ACLC%3AADC%20%231%3ASTA%20%2674%3ACMP%20%2332%3ABNE%20l%3ALDA%20%2676%3ACLC%3AADC%20%2364%3ASTA%20%2676%3ALDA%20%2677%3AADC%20%230%3ASTA%20%2677%3ALDA%20%2672%3ACLC%3AADC%20%231%3ASTA%20%2672%3ACMP%20%2310%3ABEQ%20r%3AJMP%20a%3A.r%20LDA%20%267C%3ACLC%3AADC%20%23%261%3AAND%20%23%267%3ASTA%20%267C%3AJMP%20c%3ARTS%3A%5D%3ANEXT%3AMODE%200%3AVDU23%2C1%2C0%3B0%3B0%3B0%3B%3A*FX19%5CnCALL%20g%22%7D

Worth a look to get inline asm syntax looking nicely.

```
DIM MC% 400:FOR O%=0 TO 3 STEP 3:P%=MC%:[:OPT O%:.H% EQUW &55AA:.S% EQUW &3000:.Y% EQUD &FCF0C000:EQUD &030F3FFF:.g LDA S%:STA &70:LDA S%+1:STA &71:LDY #0:.t LDA H%:STA (&70),Y:INY:LDA H%+1:STA (&70),Y:INY:BNE t:LDY #0:INC &71:BPL t:.c LDA S%:CLC
ADC #32:STA &76:LDA S%+1:STA &77:LDA #0:STA &72:.a ASL A:AND #7:STA &73:LDA &76:STA &78:LDA &77:STA &79:LDA #0:STA &74:.l LDA &78:STA &7A:LDA &79:STA &7B:LDA &73:CLC:ADC &7C:AND #&7:TAY:LDA Y%,Y:LDY #0:STA (&7A),Y:INY:STA (&7A),Y:INY:STA (&7A),Y:INY:STA (&7A),Y
INY:STA (&7A),Y:INY:STA (&7A),Y:INY:STA (&7A),Y:INY:STA (&7A),Y:LDA #&F0:BIT &74:BNE e:LDA #&2:BIT &72:BNE k:JMP f:.e LDA #&2:BIT &72:BNE f:JMP k:.f LDA &73:CLC:ADC #1:AND #7:STA &73:JMP i:.k LDA &73:CLC:ADC #7:AND #7:STA &73:.i CLC:LDA &78:ADC #&80:STA &78
LDA &79:ADC #2:STA &79:LDA &74:CLC:ADC #1:STA &74:CMP #32:BNE l:LDA &76:CLC:ADC #64:STA &76:LDA &77:ADC #0:STA &77:LDA &72:CLC:ADC #1:STA &72:CMP #10:BEQ r:JMP a:.r LDA &7C:CLC:ADC #&1:AND #&7:STA &7C:JMP c:RTS:]:NEXT:MODE 0:VDU23,1,0;0;0;0;:*FX19
CALL g
```
(raw output)

**Comment by mattgodbolt** [comment]
Thanks to @ojwb this is a _lot_ better. Still seeing "invalid token" on variable accesses
![Screenshot from 2020-12-07 09-46-40](https://user-images.githubusercontent.com/633973/101372099-20578a80-3871-11eb-81d8-9fc9dae6d68c.png)

**Comment by ojwb** [comment]
I know, but I thought it was worth sending what I had so that if anyone else looks at this they can start from a better point.

It should at least not indicate errors in valid assembler (not sure if it's worth the effort to teach it what the valid instructions and addressing modes are).
