### ISSUE TITLE
Don't suggest keywords which are invalid in a program

### ISSUE THREAD

**Issue by ojwb** [mattgodbolt/owlet-editor#34]
Some keywords don't work in a program so it's not helpful to suggest them as completions.

It seems the list is `AUTO`, `LIST`, `RENUMBER`, `NEW`, `OLD`, `LOAD`, `SAVE` but I may have missed some (or contexts where some of those work).  (Note `CHAIN` and `RUN` **are** valid in a program.)

**Comment by mattgodbolt** [comment]
Right! These are easy enough to do. Moving forward suggesting `PRINT` halfway through a line should be avoided too. I _think_ we get some clues for those in the "flags" of the tokenisation table (which we parse but don't use yet). e.g. http://www.benryves.com/bin/bbcbasic/manual/Appendix_Tokeniser.htm stuff in there we aren't yet using.

**Comment by ojwb** [comment]
Those flags seem very useful.  Looking at that table, `DELETE` is missing from my original list.

**Comment by ojwb** [comment]
I've opened a PR to fix my original report and new issue #82 for Matt's suggestion to be context sensitive.

**Comment by mattgodbolt** [comment]
Will be deploying shortly: https://github.com/mattgodbolt/owlet-editor/actions/runs/1877654355
