### ISSUE TITLE
Support "conditional" flag in highlighting abbreviated tokens

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/owlet-editor#36]
We should consider the `C` bit of the token table for e.g. `FALSE`, `EXT`... http://www.benryves.com/bin/bbcbasic/manual/Appendix_Tokeniser.htm

Concretly, `TIMER=1` is parsed as a variable, not `<TIME>R=1`

See #34

**Comment by ojwb** [comment]
Note this C bit also seems to have an effect even for an abbreviated token - e.g. this gives "No such variable":

```
F.A=H.TO8^5:?A=42:N.
```

It works if you add a space after `H.`.

It'd be nice if the editor highlighted `H.` in red or something like that in this case - I still get caught out by this quirk sometimes.

**Comment by mattgodbolt** [comment]
Partially addressed by baee73d6b0109c027e01b24d85828ee105458613 but not for the special case of abbreviated tokens. Will update this bug to handle that
