### ISSUE TITLE
* command should last to end of line

### ISSUE THREAD

**Issue by ojwb** [mattgodbolt/owlet-editor#37]
Currently the highlighter seems to switch back to BASIC if it sees a `:` in a `*` command:

```
*FX19:PRINT
```

**Comment by mattgodbolt** [comment]
This is going to be a fun one to do :) Context-sensitivity of symbols is a bit more fun in the (editor) tokeniser.

**Comment by ojwb** [comment]
It seems `:` doesn't end the content of a `REM` so perhaps `*` can work like that does?

**Comment by mattgodbolt** [comment]
That's not the problem, it's discriminating `*` in the middle of a line (`3*2`) vs one at the start or after a colon. `REM` is always `REM` (in theory). I think we'll need to make the editor tokeniser have a mode for "First part of a statement" vs the rest, to solve this.

**Comment by ojwb** [comment]
Oh I see - I was thinking you mean the context-sensitivity of `:`.

Yes, the [`Start flag` in the token table](http://www.benryves.com/bin/bbcbasic/manual/Appendix_Tokeniser.htm) seems the right thing for this - it even mentions `*`:

>`*` - disables the tokeniser if encountered at the start of the statement.

**Comment by mattgodbolt** [comment]
With a new version of monaco, we should be able to do this: https://github.com/microsoft/monaco-editor/issues/2265

**Comment by mattgodbolt** [comment]
(the change to look for being merged is https://github.com/microsoft/vscode/commit/5cc0aa284968c66b0075ac3b89a70c2edb10b891 )

**Comment by ojwb** [comment]
Still present - here's a better reproducer (`*.:0` is actually a useful command, at least if there's a disc in the drive) as a handy URL:

https://bbcmic.ro/#%7B%22v%22%3A1%2C%22program%22%3A%22*.%3A0%22%7D
