### ISSUE TITLE
Reports of not working on FF 75

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/owlet-editor#44]
```
SyntaxError: invalid regular expression flag s
```

**Comment by mattgodbolt** [comment]
(via @cppchedy)

**Comment by mattgodbolt** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1579867 suggests it doesn't support `/s` ?

**Comment by mattgodbolt** [comment]
Oldest version of FF I could quickly install was 78.5, and that works. Will try finding older versions...

**Comment by mattgodbolt** [comment]
Confirmed using https://www.browserling.com/browse/win/7/firefox/75/https%3A%2F%2Fbbcmic.ro though; bleuch

**Comment by ojwb** [comment]
I checked using the browserling link and owlet works OK with FF 75 now.

Looks like the only use of `/s` was removed by 5b05cfd10aea039f4ee95712121507ac177d3713 to address #63.

So I think this can be closed now.

**Comment by ojwb** [comment]
@mattgodbolt As above, I believe this can be closed now.

**Comment by mattgodbolt** [comment]
Thanks!
