### ISSUE TITLE
Blank screen for older browser versions

### ISSUE THREAD

**Issue by 8bitkick** [mattgodbolt/owlet-editor#63]
See

"About" says "Firefox Quantum 68.9.0esr (64-bit)". (It's on slackware linux).  I just get a blank page.

https://twitter.com/ArnoldLabour/status/1345060692500611076?s=20

**Comment by 8bitkick** [comment]
Fixed for the platform in question

**Comment by mattgodbolt** [comment]
Nice! Thanks... I'll add a polfill for this
