### ISSUE TITLE
Previous screen contents show through MODE3 stripes

### ISSUE THREAD

**Issue by ojwb** [mattgodbolt/owlet-editor#69]
E.g. this example results in a mixture of red, black and white in the stripes between the character rows (seen with Firefox):

```
MODE2:C.129:CLS:MODE6:P."HELLO WORLD":V.279;0;0;0;0
```
link: https://bbcmic.ro/#%7B%22v%22%3A1%2C%22program%22%3A%22MODE2%3AC.129%3ACLS%3AMODE3%3AP.%5C%22HELLO%20WORLD%5C%22%3AV.279%3B0%3B0%3B0%3B0%22%7D

A similar effect can be seen in `MODE6` and also `MODE7` (in the bottom few scanlines) - just change the `MODE3` in the example code.  From hacking on the bot code these areas come out transparent when we grab the screen contents from jsbeeb,  and I suspect that's related to what's happening here.

I also notice in `MODE5` that there's a stripe of red down the left side of the screen and some other glitchy pixels along the bottom.

I couldn't seem to reproduce in a quick test in chromium, so this may be browser-dependent.

**Comment by ojwb** [comment]
I don't seem to be able to reproduce this with Firefox 88.0, so I guess it was a firefox bug and has been fixed in the meantime.

Closing - I'll reopen if I see it again.

**Comment by ojwb** [comment]
Oh, or it could be it was fixed in owlet itself or in  jsbeeb or some other dependency.  I've just had a quick look at owlet and jsbeeb, but didn't spot anything likely.

**Comment by mattgodbolt** [comment]
We've definitely got a jsbeeb gremlin of this shape somewhere...it's been reported a number of times but we've never been able to pin it down.
