### ISSUE TITLE
Export SSD with pound signs in DATA statements

### ISSUE THREAD

**Issue by nergix** [mattgodbolt/owlet-editor#77]
Hi,

Using the live version at bbcmic.ro, with this simple program:

https://bbcmic.ro/#%7B%22v%22%3A1%2C%22program%22%3A%22FOR%20X%3D1%20TO%204%5CnREAD%20A%24%5CnPRINT%20%5C%22%20%5C%22%2CA%24%5CnNEXT%5CnDATA%20A%2CB%2C%C2%A3%2CC%5Cn%22%7D

If you then click Share and export to an SSD disc image, instances of '£' in the DATA statement are replaced by FALSE tokens when the SSD is loaded. I've tested the SSD in both jsbeeb and b-em with the same result, so it seems that this is an owlet problem.

Thanks.

**Comment by ojwb** [comment]
I've submitted a PR to fix this.

Note however that a £ in Owlet is Unicode character U+00A3, whereas a pound sign on a BBC micro is character 96 (see appendix C of the User Guide.  In standard ASCII and Unicode, character 96 is `.

The bot just converts Unicode characters by taking the bottom 8 bits, so U+00A3 -> 0xA3 which is 163.  In most screen modes that's a user defined character which is blank by default, but in MODE7 (the default screen mode) the top bit set characters are a copy of the teletext character set from the teletext chip, but without some adjustments that the OS makes to the version below 128 (the OS swaps around 35, 95 and 96).  163 is 128 + 35 and 35 is a hash (#), and the teletext chip's character set has £ where ASCII has #.  See appendix B of the User Guide for the MODE7 character chart.

The upshot of all this is that your example running in MODE7 prints a £, but if you add e.g. `MODE4` at the top it won't.

If you want a real BBC Micro £ then you need to use ` in Owlet.
