### ISSUE TITLE
Examples not loading

### ISSUE THREAD

**Issue by GilesDMiddleton** [mattgodbolt/owlet-editor#98]
I'm totally just a transient hobo passing by trying things out, and i wanted to try some of the examples, but when I click of them, it takes me to Owlet but doesn't load the source code.
from https://www.bbcmicrobot.com/owlet-test2.html
I click the first example which is the URL 
https://bbcmic.ro/?load=1230644568326053888
But it doesn't load and brings me to the hello world example of Owlet.

**Comment by brnrds** [comment]
+1, same behaviour.

**Comment by andypiper** [comment]
Ah! Not just me then.

Maybe the "awesome examples" link should now go straight to [the main BBC Micro Bot page](https://www.bbcmicrobot.com/) which has a working gallery?

I would be interested to see the original example code from the 1000 awesome examples page though!

**Comment by andypiper** [comment]
Where are the 1000 awesome demos stored?
AFAICT that's loading a program based on the filename of an image in the gallery, but I can't find where those are located.

It looks like the behaviour (fallback to the first example) is to do with the code not being able to load state from somewhere.
